# Generated by Django 4.1.6 on 2023-02-02 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phonebookapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phonebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone_no', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='number',
            name='name_id',
        ),
        migrations.DeleteModel(
            name='Names',
        ),
        migrations.DeleteModel(
            name='Number',
        ),
    ]
